baseurl = "https://maximilianrohde.com"
title = "Max Rohde"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Max"

[params]
    author = "Max Rohde"
    description = "Max Rohde' personal website"
    keywords = ""
    info = "Biostatistics MS Student @ Vanderbilt"
    avatarurl = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideFooter = true
    hideCredits = true
    hideCopyright = true
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/maxdrohde/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/maxrohde8/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Publications"
            weight = 3
            url = "publications/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"

            [[languages.en.menu.main]]
            name = "Resume"
            weight = 6
            url = "/files/rohde_resume_2020.pdf"
